# Generated by Django 3.0.8 on 2020-08-11 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milo_webpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leafs_shape',
            name='examples_of_shape',
            field=models.ImageField(upload_to='images'),
        ),
    ]
