# Generated by Django 3.0.8 on 2020-08-11 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milo_webpage', '0002_auto_20200811_2017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leafs_Count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leafs_count_examples', models.ImageField(upload_to='images')),
            ],
        ),
    ]
